/**
 * The "How this works" panel.
 *
 * Not optional, and not decoration: a Detronics tool that only outputs a number is
 * unfinished. Each panel is the concept in plain language, the rule it follows, and that
 * rule worked through with whatever is currently on screen.
 *
 * The worked example is generated by the pure modules - `explainTiming` and
 * `explainVisemes` in js/lipsync.js - so it cannot drift out of step with the numbers it
 * is explaining, and it is covered by the same tests.
 */

import { el } from './dom.js';
import { explainTiming, explainVisemes } from '../lipsync.js';
import { getScheme } from '../visemes.js';
import { formatDuration } from '../timecode.js';

function panel({ title, plain, formula, worked }, { open = false } = {}) {
  return el('details', { class: 'explain', open }, [
    el('summary', { class: 'explain__summary', text: title }),
    el('div', { class: 'explain__body' }, [
      el('p', { class: 'explain__plain', text: plain }),
      formula ? el('pre', { class: 'explain__formula value', text: formula }) : null,
      worked ? el('pre', { class: 'explain__worked value', text: worked }) : null,
    ]),
  ]);
}

/* ---------------------------------------------------------------------------- *
 * One panel per tool
 * ---------------------------------------------------------------------------- */

export function explainAnimate(track) {
  return el('div', { class: 'explain-stack' }, [
    panel({ title: 'How the timing is worked out', ...explainTiming(track) }, { open: true }),
    panel({ title: 'Why there are only a dozen mouth shapes', ...explainVisemes(track.schemeId) }),
    panel({
      title: 'How this differs from Rhubarb Lip Sync',
      plain:
        'Rhubarb Lip Sync listens to a recording and recognises the sounds in it, which is why it ' +
        'needs the recording before it can tell you anything. This tool starts from the script ' +
        'instead: it predicts the sounds from the spelling and models how long each one takes. ' +
        'That means you can block out a performance before a single line has been recorded — and ' +
        'when the recording does arrive, loading it fits the track onto the real take.',
      formula: [
        'Rhubarb     audio  -> recognised phonemes -> cues   (measured)',
        'This tool   script -> predicted phonemes  -> cues   (modelled)',
        '            + audio -> silences           -> fitted cues',
      ].join('\n'),
      worked:
        'What is exact either way: which shape follows which, and in what order.\n' +
        'What is modelled here: how long each one is held.\n' +
        'What fixes it: loading the recording, or nudging a cue by hand.',
    }),
  ]);
}

export function explainBreakdown(track) {
  const overridden = track.words.filter((w) => w.source === 'override').length;
  const guessed = track.words.filter((w) => w.source === 'rules').length;

  return el('div', { class: 'explain-stack' }, [
    panel({
      title: 'How a word becomes mouth shapes',
      plain:
        'English spelling is not a function of its pronunciation — read and read are the same six ' +
        'letters and two different words — so no rule set can ever be complete. This one uses a ' +
        'few hundred spelling rules with an exception list for the words that break them, which ' +
        'gets most of a normal script right. The rest is why every row here is editable: correct a ' +
        'word once and the correction is remembered with the project.',
      formula: [
        'spelling  -> exception list, else spelling rules  -> phonemes',
        'phonemes  -> the scheme’s viseme map              -> mouth shapes',
        'identical neighbours merge; nothing is held under minHold',
      ].join('\n'),
      worked: [
        `${track.words.length} words in this script`,
        `${track.words.filter((w) => w.source === 'lexicon').length} came from the exception list`,
        `${guessed} came from the spelling rules`,
        `${overridden} you have corrected by hand`,
      ].join('\n'),
    }, { open: true }),
  ]);
}

export function explainMouths(schemeId, mouthSet, cover) {
  const scheme = getScheme(schemeId);

  return el('div', { class: 'explain-stack' }, [
    panel({ title: 'Why there are only a dozen mouth shapes', ...explainVisemes(schemeId) }, { open: true }),
    panel({
      title: 'What to draw, and in what order',
      plain:
        'If you are drawing a set from scratch, draw them in this order. The closed mouth first, ' +
        'because a missing P is the one fault every viewer notices. Then the wide open vowel and ' +
        'the teeth-together consonant, which between them cover most frames of most lines. After ' +
        'those four or five the returns fall away quickly — which is exactly why a viseme set is ' +
        'a dozen pictures rather than forty.',
      formula: [
        '1  closed          B M P        the one nobody forgives',
        '2  wide open       A E I        the biggest movement',
        '3  teeth together  C D G K N    the most frequent',
        '4  puckered        Q W          the most distinct',
        '5  teeth on lip    F V          obvious when missing',
      ].join('\n'),
      worked: [
        `${scheme.name}`,
        `${cover.assigned.length} of ${cover.total} mouth shapes have artwork`,
        cover.brows || cover.eyes
          ? `${cover.brows} brow and ${cover.eyes} eye pictures on the character`
          : 'no brow or eye pictures yet',
        cover.missing.length
          ? `still to draw: ${cover.missing.join(', ')}`
          : 'every mouth shape is drawn',
      ].join('\n'),
    }),
  ]);
}

export function explainExport(track, lossy) {
  return el('div', { class: 'explain-stack' }, [
    panel({
      title: 'What the exported file contains',
      plain:
        'Every format here is a list of the same thing: an instant, and the shape to be showing ' +
        'from that instant on. The Rhubarb formats are byte-for-byte what Rhubarb Lip Sync itself ' +
        'writes, so anything already built around it — a Blender add-on, a Moho rig, somebody’s ' +
        'script — takes this without knowing the difference.',
      formula: [
        'TSV    0.00\\tX          time, tab, shape',
        'JSON   {start, end, value}   contiguous cues',
        'XML    <mouthCue start end>  the same, in tags',
        'Moho   0 rest               frame number, switch name',
      ].join('\n'),
      worked: [
        `${track.cues.length} cues over ${formatDuration(track.duration)} at ${track.settings.fps} fps`,
        `${track.stats.distinctShapes} distinct shapes used`,
        lossy.length
          ? `flattened on export: ${lossy.map((l) => `${l.merged.join(' + ')} → ${l.name}`).join(', ')}`
          : 'no shape detail is lost in this format',
      ].join('\n'),
    }, { open: true }),
  ]);
}

export { panel as explainPanel };
